CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'turnos') THEN
        CREATE SCHEMA turnos;
    END IF;
END $EF$;

CREATE TABLE turnos."Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE turnos."Usuarios" (
    "Id" uuid NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

CREATE TABLE turnos."RolClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RolClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RolClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES turnos."Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE turnos."UsuarioClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UsuarioClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UsuarioClaims_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES turnos."Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE turnos."UsuarioRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UsuarioRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UsuarioRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES turnos."Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UsuarioRoles_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES turnos."Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE turnos."UsuarioTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UsuarioTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UsuarioTokens_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES turnos."Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE turnos."UsusarioLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UsusarioLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UsusarioLogins_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES turnos."Usuarios" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RolClaims_RoleId" ON turnos."RolClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON turnos."Roles" ("NormalizedName");

CREATE INDEX "IX_UsuarioClaims_UserId" ON turnos."UsuarioClaims" ("UserId");

CREATE INDEX "IX_UsuarioRoles_RoleId" ON turnos."UsuarioRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON turnos."Usuarios" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON turnos."Usuarios" ("NormalizedUserName");

CREATE INDEX "IX_UsusarioLogins_UserId" ON turnos."UsusarioLogins" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250402034806_Identity', '9.0.3');

CREATE TABLE turnos."DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250402045839_DataProtection', '9.0.3');

ALTER TABLE turnos."Usuarios" ADD "Kind" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250413122525_Add_Alumno_Personal', '9.0.3');

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'turnos') THEN
        CREATE SCHEMA turnos;
    END IF;
END $EF$;

CREATE TYPE turnos.estado_fila AS ENUM ('abierta', 'cerrada');
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'turnos') THEN
        CREATE SCHEMA turnos;
    END IF;
END $EF$;

CREATE TYPE turnos.estado_turno AS ENUM ('atendido', 'atendiendo', 'cancelado', 'pendiente');

CREATE TABLE turnos."Filas" (
    "Id" uuid NOT NULL,
    "PersonalId" uuid NOT NULL,
    "Name" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Estado" turnos.estado_fila NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_Filas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Filas_Usuarios_PersonalId" FOREIGN KEY ("PersonalId") REFERENCES turnos."Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE turnos."Turnos" (
    "FilaId" uuid NOT NULL,
    "AlumnoId" uuid NOT NULL,
    "Lugar" bigint NOT NULL,
    "Estado" turnos.estado_turno NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_Turnos" PRIMARY KEY ("AlumnoId", "FilaId", "Lugar"),
    CONSTRAINT "FK_Turnos_Filas_FilaId" FOREIGN KEY ("FilaId") REFERENCES turnos."Filas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Turnos_Usuarios_AlumnoId" FOREIGN KEY ("AlumnoId") REFERENCES turnos."Usuarios" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Filas_PersonalId" ON turnos."Filas" ("PersonalId");

CREATE INDEX "IX_Turnos_FilaId" ON turnos."Turnos" ("FilaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250413202414_Add_Fila_Turno', '9.0.3');

ALTER TABLE turnos."Filas" ALTER COLUMN "PasswordHash" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250415143834_Fila_PasswordHash_Null', '9.0.3');

ALTER TABLE turnos."Usuarios" ADD "Name" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250415171027_Add_User_Name_Prop', '9.0.3');

ALTER TABLE turnos."Turnos" ADD "AttendedAt" timestamp with time zone;

ALTER TABLE turnos."Turnos" ADD "CompletedAt" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250501183359_Completed_Attended_Turno', '9.0.3');

ALTER TABLE turnos."Filas" ADD "EstimatedAttentionTime" interval NOT NULL DEFAULT INTERVAL '00:00:00';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250501232415_EstimateTime_Fila', '9.0.3');

INSERT INTO turnos."Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('0196db06-2330-7fb8-84f1-2d6bc594269e', NULL, 'Alumno', 'ALUMNO');
INSERT INTO turnos."Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('0196db06-2334-7969-9f83-0e1b575a7878', NULL, 'Personal', 'PERSONAL');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250516213536_SeedRoles', '9.0.3');

COMMIT;

